# NOTE: Before deploying to a production environment, please review the documentation -> https://aka.ms/self-hosted-gateway-production
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gw1-env
data:
  config.service.endpoint: "https://daprapimdemo.management.azure-api.net/subscriptions/2865c7d1-29fa-485a-8862-717377bdbf1b/resourceGroups/mchmarny/providers/Microsoft.ApiManagement/service/daprapimdemo?api-version=2019-12-01"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gw1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gw1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: gw1
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "gw1"
        dapr.io/config: "tracing"
        dapr.io/log-as-json: "true"
        dapr.io/log-level: "debug"
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: gw1
        image: mcr.microsoft.com/azure-api-management/gateway:beta
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8081
        readinessProbe:
          httpGet:
            path: /internal-status-0123456789abcdef
            port: http
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        env:
        - name: config.service.auth
          valueFrom:
            secretKeyRef:
              name: gw1-token
              key: value
        envFrom:
        - configMapRef:
            name: gw1-env
---
apiVersion: v1
kind: Service
metadata:
  name: gw1
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8081
  selector:
    app: gw1