openapi: 3.0.1
info:
  title: dapr
  version: '1.0'
servers:
  - url: http://dapr-apim-demo.azure-api.net
  - url: https://dapr-apim-demo.azure-api.net
paths:
  /dapr-echo:
    post:
      summary: Invoke Dapr service
      description: Invoke service using Dapr API
      operationId: echo
      requestBody:
        content:
          application/json:
            example:
              message: hello
      responses:
        '200':
          description: ''
  /dapr-topic:
    post:
      summary: Post to Dapr pub/sub topic
      description: Invoke service using Dapr API
      operationId: events
      requestBody:
        content:
          application/json:
            example:
              message: hello
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]

