openapi: 3.0.1
info:
  title: dapr
  version: '1.0'
servers:
  - url: http://dapr-apim-demo.azure-api.net
  - url: https://dapr-apim-demo.azure-api.net
paths:
  /echo:
    post:
      summary: Echo Service
      description: Invoke service using Dapr API
      operationId: echo
      requestBody:
        content:
          application/json:
            example:
              message: hello
      responses:
        '200':
          description: ''
  /message:
    post:
      summary: Message Topic
      description: Post to topic using Dapr API
      operationId: message
      requestBody:
        content:
          application/json:
            example:
              content: hello
      responses:
        '200':
          description: ''
  /query:
    post:
      summary: Query Binding
      description: Query output binding using Dapr API
      operationId: query
      requestBody:
        content:
          application/json:
            example:
              query: serverless
              lang: en
              result: recent
      responses:
        '200':
          description: ''